export const UPDATE_THEME = "UPDATE_THEME";
export const UPDATE_RELEASE_COUNTDOWN = "UPDATE_RELEASE_COUNTDOWN";
export const UPDATE_SIGN_UP_FORM = "UPDATE_SIGN_UP_FORM";
export const UPDATE_LOADING = "UPDATE_LOADING";

export const MY_PROFILE = {
  GENERAL: {
    UPDATE_OPENED_STATS: "MY_PROFILE_GENERAL_UPDATE_OPENED_STATS",
    UPDATE_OPENED_FRIENDS_LIST: "MY_PROFILE_GENERAL_UPDATE_OPENED_FRIENDS_LIST",
  },
  MY_RECIPES: {
    UPDATE_DIVISION: "MY_PROFILE_MY_RECIPES_UPDATE_DIVISION",
    UPDATE_SEARCH_VALUE: "MY_PROFILE_MY_RECIPES_UPDATE_SEARCH_VALUE",
    UPDATE_ORDER_OF_RESULTS: {
      ASC: "MY_PROFILE_MY_RECIPES_UPDATE_ORDER_OF_RESULTS_ASCENDING",
      DESC: "MY_PROFILE_MY_RECIPES_UPDATE_ORDER_OF_RESULTS_DESCENDING",
    },
    UPDATE_TYPE_OF_RESULTS: "MY_PROFILE_MY_RECIPES_UPDATE_TYPE_OF_RESULTS",
    UPDATE_NUMBER_OF_RESULTS: "MY_PROFILE_MY_RECIPES_UPDATE_NUMBER_OF_RESULTS",
    UPDATE_RESULTS: "MY_PROFILE_MY_RECIPES_UPDATE_RESULTS",
  },
};
